embfeat: -1
embtype: codebert
gatdropout: 0.2
gnntype: gat2layer
hdropout: 0.3
hfeat: 512
loss: ce
lr: 0.0001
lstm_dropout: 0.2
lstm_layers: 2
methodlevel: false
mlpdropout: 0.2
model: mlponly
multitask: linemethod
nsampling: true
num_heads: 4
random: false
scea: 0.5
stmtweight: 1
